#include "YasuFastAudioCore.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <limits>
#include <sstream>
#include <string>

#include <opus.h>

#include "voip/tgcalls/YasuMeasurementGate.h"

namespace tgcalls {

namespace {

constexpr int kMaxStreams = 32;

// Very small packet reorder window.
// We prefer a tiny amount of loss/stutter over waiting for late packets.
constexpr int kPacketSlots = 6;
constexpr int kMaxPayload = 1600;

// 1024 mono frames ~= 21.3 ms at 48 kHz.
// If the producer gets ahead, old PCM is dropped to prevent latency growth.
constexpr int kStreamRingFrames = 1024;

constexpr int kOutputChunk = 480;

// Safe maximum Opus frame size.
// Actual Group Call packets are normally 10 ms = 480 samples.
constexpr int kDecodeSamples = 5760;

using Clock = std::chrono::steady_clock;

uint64_t NowUs() {
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::microseconds>(
            Clock::now().time_since_epoch()).count());
}

inline bool SeqAhead(uint16_t sequence, uint16_t expected) {
    return static_cast<int16_t>(
        static_cast<uint16_t>(sequence - expected)) > 0;
}

inline bool SeqBehind(uint16_t sequence, uint16_t expected) {
    return static_cast<int16_t>(
        static_cast<uint16_t>(sequence - expected)) < 0;
}

inline uint16_t SeqForwardDistance(
    uint16_t sequence,
    uint16_t expected) {
    return static_cast<uint16_t>(sequence - expected);
}

struct Packet {
    bool valid = false;
    uint16_t sequence = 0;
    uint32_t timestamp = 0;
    uint16_t size = 0;

    // Real arrival time of the RTP packet.
    uint64_t arrival_us = 0;

    uint8_t data[kMaxPayload]{};
};

struct Stream {
    std::atomic<bool> active{false};

    uint32_t ssrc = 0;

    OpusDecoder* decoder = nullptr;

    bool have_sequence = false;
    uint16_t next_sequence = 0;

    bool have_timestamp = false;
    uint32_t next_timestamp = 0;

    Packet packets[kPacketSlots];

    // Mono PCM ring after stereo Opus downmix.
    int16_t pcm[kStreamRingFrames]{};

    // Arrival timestamp associated with each PCM sample.
    // 0 means the sample was generated by PLC and has no real
    // RTP arrival timestamp.
    uint64_t pcm_time_us[kStreamRingFrames]{};

    std::atomic<uint32_t> pcm_read{0};
    std::atomic<uint32_t> pcm_write{0};

    // Written by packet path, read only for diagnostics.
    std::atomic<uint64_t> last_packet_us{0};
};

struct Stats {
    uint64_t started_us = 0;

    std::atomic<uint64_t> packets_received{0};
    std::atomic<uint64_t> packets_decoded{0};
    std::atomic<uint64_t> packets_plc{0};
    std::atomic<uint64_t> packets_fec{0};
    std::atomic<uint64_t> packets_late{0};
    std::atomic<uint64_t> packets_dropped{0};
    std::atomic<uint64_t> packets_reordered{0};
    std::atomic<uint64_t> packets_decode_failed{0};

    std::atomic<uint64_t> decode_count{0};
    std::atomic<uint64_t> decode_cost_us{0};
    std::atomic<uint64_t> decode_cost_min_us{
        std::numeric_limits<uint64_t>::max()};
    std::atomic<uint64_t> decode_cost_max_us{0};

    // Packet arrival -> beginning/end of decoded PCM buffering.
    std::atomic<uint64_t> packet_to_pcm_count{0};
    std::atomic<uint64_t> packet_to_pcm_us{0};
    std::atomic<uint64_t> packet_to_pcm_min_us{
        std::numeric_limits<uint64_t>::max()};
    std::atomic<uint64_t> packet_to_pcm_max_us{0};

    // RTP arrival -> AAudio ReadPcm.
    std::atomic<uint64_t> packet_to_play_count{0};
    std::atomic<uint64_t> packet_to_play_us{0};
    std::atomic<uint64_t> packet_to_play_min_us{
        std::numeric_limits<uint64_t>::max()};
    std::atomic<uint64_t> packet_to_play_max_us{0};

    std::atomic<uint64_t> pcm_frames_written{0};
    std::atomic<uint64_t> pcm_frames_read{0};

    // Real callback starvation.
    std::atomic<uint64_t> pcm_underruns{0};

    // Old PCM discarded because ring was full.
    std::atomic<uint64_t> pcm_overruns{0};
    std::atomic<uint64_t> pcm_overrun_frames{0};

    std::atomic<uint64_t> residence_count{0};
    std::atomic<uint64_t> residence_us{0};
    std::atomic<uint64_t> residence_min_us{
        std::numeric_limits<uint64_t>::max()};
    std::atomic<uint64_t> residence_max_us{0};

    std::atomic<uint64_t> callback_count{0};
    std::atomic<uint64_t> callback_frames{0};
    std::atomic<uint64_t> callback_cost_us{0};
    std::atomic<uint64_t> callback_cost_min_us{
        std::numeric_limits<uint64_t>::max()};
    std::atomic<uint64_t> callback_cost_max_us{0};

    std::atomic<uint64_t> max_ring_depth{0};
    std::atomic<uint64_t> active_streams_peak{0};

    void Reset() {
        started_us = NowUs();

        packets_received.store(0);
        packets_decoded.store(0);
        packets_plc.store(0);
        packets_fec.store(0);
        packets_late.store(0);
        packets_dropped.store(0);
        packets_reordered.store(0);
        packets_decode_failed.store(0);

        decode_count.store(0);
        decode_cost_us.store(0);
        decode_cost_min_us.store(
            std::numeric_limits<uint64_t>::max());
        decode_cost_max_us.store(0);

        packet_to_pcm_count.store(0);
        packet_to_pcm_us.store(0);
        packet_to_pcm_min_us.store(
            std::numeric_limits<uint64_t>::max());
        packet_to_pcm_max_us.store(0);

        packet_to_play_count.store(0);
        packet_to_play_us.store(0);
        packet_to_play_min_us.store(
            std::numeric_limits<uint64_t>::max());
        packet_to_play_max_us.store(0);

        pcm_frames_written.store(0);
        pcm_frames_read.store(0);

        pcm_underruns.store(0);
        pcm_overruns.store(0);
        pcm_overrun_frames.store(0);

        residence_count.store(0);
        residence_us.store(0);
        residence_min_us.store(
            std::numeric_limits<uint64_t>::max());
        residence_max_us.store(0);

        callback_count.store(0);
        callback_frames.store(0);
        callback_cost_us.store(0);
        callback_cost_min_us.store(
            std::numeric_limits<uint64_t>::max());
        callback_cost_max_us.store(0);

        max_ring_depth.store(0);
        active_streams_peak.store(0);
    }

    static void AddMin(
        std::atomic<uint64_t>& value,
        uint64_t v) {

        uint64_t old =
            value.load(std::memory_order_relaxed);

        while (v < old &&
               !value.compare_exchange_weak(
                   old,
                   v,
                   std::memory_order_relaxed,
                   std::memory_order_relaxed)) {
        }
    }

    static void AddMax(
        std::atomic<uint64_t>& value,
        uint64_t v) {

        uint64_t old =
            value.load(std::memory_order_relaxed);

        while (v > old &&
               !value.compare_exchange_weak(
                   old,
                   v,
                   std::memory_order_relaxed,
                   std::memory_order_relaxed)) {
        }
    }

    void DecodeCost(uint64_t us) {
        decode_count.fetch_add(1);
        decode_cost_us.fetch_add(us);
        AddMin(decode_cost_min_us, us);
        AddMax(decode_cost_max_us, us);
    }

    void PacketToPcm(uint64_t us) {
        packet_to_pcm_count.fetch_add(1);
        packet_to_pcm_us.fetch_add(us);
        AddMin(packet_to_pcm_min_us, us);
        AddMax(packet_to_pcm_max_us, us);
    }

    void PacketToPlay(uint64_t us) {
        packet_to_play_count.fetch_add(1);
        packet_to_play_us.fetch_add(us);
        AddMin(packet_to_play_min_us, us);
        AddMax(packet_to_play_max_us, us);
    }

    void Residence(uint64_t us) {
        residence_count.fetch_add(1);
        residence_us.fetch_add(us);
        AddMin(residence_min_us, us);
        AddMax(residence_max_us, us);
    }

    void Callback(uint64_t us, int frames) {
        callback_count.fetch_add(1);
        callback_frames.fetch_add(
            static_cast<uint64_t>(frames));
        callback_cost_us.fetch_add(us);
        AddMin(callback_cost_min_us, us);
        AddMax(callback_cost_max_us, us);
    }
};

}  // namespace

struct YasuFastAudioCore::Impl {
    std::atomic<bool> enabled{false};

    // Serializes packet/decode/reset operations.
    // The AAudio callback never takes this lock.
    std::atomic_flag processing = ATOMIC_FLAG_INIT;

    Stream streams[kMaxStreams];
    Stats stats;

    void Lock() {
        while (processing.test_and_set(
            std::memory_order_acquire)) {
        }
    }

    void Unlock() {
        processing.clear(std::memory_order_release);
    }

    bool Measurements() const {
        return YasuMeasurementsEnabled();
    }

    Stream* Find(uint32_t ssrc) {
        for (auto& stream : streams) {
            if (stream.active.load(
                    std::memory_order_acquire) &&
                stream.ssrc == ssrc) {
                return &stream;
            }
        }

        return nullptr;
    }

    Stream* Create(uint32_t ssrc) {
        Stream* stream = nullptr;

        // Prefer an inactive slot.
        for (auto& item : streams) {
            if (!item.active.load(
                    std::memory_order_acquire)) {
                stream = &item;
                break;
            }
        }

        // If all 32 streams are occupied, replace slot 0.
        // This is intentionally bounded and allocation-free.
        if (!stream) {
            stream = &streams[0];

            if (stream->decoder) {
                opus_decoder_destroy(stream->decoder);
                stream->decoder = nullptr;
            }

            stats.packets_dropped.fetch_add(1);
        }

        int error = OPUS_OK;

        stream->decoder =
            opus_decoder_create(
                48000,
                2,
                &error);

        if (stream->decoder && error == OPUS_OK) {
            // Match the low-complexity Opus configuration used by
            // the optimized Yasu audio path.
            opus_decoder_ctl(
                stream->decoder,
        }

        if (!stream->decoder ||
            error != OPUS_OK) {

            stream->decoder = nullptr;

            stream->active.store(
                false,
                std::memory_order_release);

            stats.packets_dropped.fetch_add(1);

            return nullptr;
        }

        std::memset(
            stream->packets,
            0,
            sizeof(stream->packets));

        std::memset(
            stream->pcm,
            0,
            sizeof(stream->pcm));

        std::memset(
            stream->pcm_time_us,
            0,
            sizeof(stream->pcm_time_us));

        stream->pcm_read.store(
            0,
            std::memory_order_release);

        stream->pcm_write.store(
            0,
            std::memory_order_release);

        stream->ssrc = ssrc;

        stream->have_sequence = false;
        stream->next_sequence = 0;

        stream->have_timestamp = false;
        stream->next_timestamp = 0;

        stream->last_packet_us.store(
            NowUs(),
            std::memory_order_release);

        stream->active.store(
            true,
            std::memory_order_release);

        uint64_t count = 0;

        for (const auto& item : streams) {
            if (item.active.load(
                    std::memory_order_acquire)) {
                ++count;
            }
        }

        Stats::AddMax(
            stats.active_streams_peak,
            count);

        return stream;
    }

    void PushPcm(
        Stream* stream,
        const int16_t* stereo,
        int samples,
        uint64_t source_arrival_us) {

        uint32_t write =
            stream->pcm_write.load(
                std::memory_order_relaxed);

        uint32_t read =
            stream->pcm_read.load(
                std::memory_order_acquire);

        for (int i = 0; i < samples; ++i) {
            uint32_t next =
                (write + 1) % kStreamRingFrames;

            if (next == read) {
                // Drop the oldest PCM rather than allowing
                // buffering latency to grow.
                read =
                    (read + 1) % kStreamRingFrames;

                stream->pcm_read.store(
                    read,
                    std::memory_order_release);

                stats.pcm_overruns.fetch_add(1);
                stats.pcm_overrun_frames.fetch_add(1);
            }

            const int32_t left =
                stereo[i * 2];

            const int32_t right =
                stereo[i * 2 + 1];

            // Fast stereo -> mono downmix.
            stream->pcm[write] =
                static_cast<int16_t>(
                    (left + right) / 2);

            stream->pcm_time_us[write] =
                source_arrival_us;

            write = next;
        }

        stream->pcm_write.store(
            write,
            std::memory_order_release);

        stats.pcm_frames_written.fetch_add(
            static_cast<uint64_t>(samples));

        const uint32_t depth =
            write >= read
                ? write - read
                : kStreamRingFrames - read + write;

        Stats::AddMax(
            stats.max_ring_depth,
            static_cast<uint64_t>(depth));

        if (source_arrival_us != 0 &&
            Measurements()) {

            const uint64_t now = NowUs();

            if (now >= source_arrival_us) {
                stats.PacketToPcm(
                    now - source_arrival_us);
            }
        }
    }

    int DecodePacket(
        Stream* stream,
        const uint8_t* data,
        int size,
        bool plc,
        bool fec,
        uint64_t arrival_us) {

        // Only one packet is decoded at a time because the packet
        // path is serialized. thread_local avoids stack churn.
        thread_local int16_t decoded[
            kDecodeSamples * 2];

        const uint64_t start = NowUs();

        const int samples =
            opus_decode(
                stream->decoder,
                data,
                size,
                decoded,
                kDecodeSamples,
                fec ? 1 : 0);

        const uint64_t cost =
            NowUs() - start;

        if (Measurements()) {
            stats.DecodeCost(cost);
        }

        if (samples <= 0) {
            stats.packets_decode_failed.fetch_add(1);
            return 0;
        }

        if (plc) {
            stats.packets_plc.fetch_add(1);
        } else if (fec) {
            stats.packets_fec.fetch_add(1);
            stats.packets_decoded.fetch_add(1);
        } else {
            stats.packets_decoded.fetch_add(1);
        }

        PushPcm(
            stream,
            decoded,
            samples,
            arrival_us);

        return samples;
    }

    void DecodePlc(Stream* stream) {
        DecodePacket(
            stream,
            nullptr,
            0,
            true,
            false,
            0);
    }

    Packet* FindExact(
        Stream* stream,
        uint16_t sequence) {

        for (auto& packet : stream->packets) {
            if (packet.valid &&
                packet.sequence == sequence) {
                return &packet;
            }
        }

        return nullptr;
    }

    Packet* FindNearestAhead(
        Stream* stream,
        uint16_t expected,
        uint16_t* distance_out) {

        Packet* nearest = nullptr;
        uint16_t nearest_distance = 0xffff;

        for (auto& packet : stream->packets) {
            if (!packet.valid) {
                continue;
            }

            if (!SeqAhead(
                    packet.sequence,
                    expected)) {
                continue;
            }

            const uint16_t distance =
                SeqForwardDistance(
                    packet.sequence,
                    expected);

            if (distance < nearest_distance) {
                nearest_distance = distance;
                nearest = &packet;
            }
        }

        if (distance_out) {
            *distance_out =
                nearest ? nearest_distance : 0xffff;
        }

        return nearest;
    }

    void Drain(Stream* stream) {
        if (!stream->have_sequence) {
            Packet* first = nullptr;

            // Choose the packet with the lowest forward distance
            // from any available packet. Since this is startup,
            // any valid packet is acceptable.
            for (auto& packet : stream->packets) {
                if (packet.valid) {
                    first = &packet;
                    break;
                }
            }

            if (!first) {
                return;
            }

            DecodePacket(
                stream,
                first->data,
                first->size,
                false,
                false,
                first->arrival_us);

            stream->next_sequence =
                static_cast<uint16_t>(
                    first->sequence + 1);

            stream->next_timestamp =
                first->timestamp + 480;

            stream->have_timestamp = true;

            first->valid = false;

            stream->have_sequence = true;
        }

        for (;;) {
            Packet* exact =
                FindExact(
                    stream,
                    stream->next_sequence);

            if (exact) {
                const uint16_t seq =
                    exact->sequence;

                const uint32_t timestamp =
                    exact->timestamp;

                const uint64_t arrival =
                    exact->arrival_us;

                DecodePacket(
                    stream,
                    exact->data,
                    exact->size,
                    false,
                    false,
                    arrival);

                exact->valid = false;

                stream->next_sequence =
                    static_cast<uint16_t>(
                        seq + 1);

                stream->next_timestamp =
                    timestamp + 480;

                stream->have_timestamp = true;

                continue;
            }

            uint16_t gap = 0;

            Packet* ahead =
                FindNearestAhead(
                    stream,
                    stream->next_sequence,
                    &gap);

            if (!ahead) {
                break;
            }

            /*
             * Ultra-low-latency policy:
             *
             * Do NOT wait for a missing packet.
             *
             * gap == 1:
             *   Try Opus in-band FEC from the packet that arrived.
             *   This can reconstruct the missing 10 ms without adding
             *   another network wait.
             *
             * gap > 1:
             *   Generate PLC immediately for missing frames.
             *
             * This intentionally trades a small amount of possible
             * stutter for lower playback latency.
             */
            if (gap == 1) {
                const uint16_t sequence =
                    ahead->sequence;

                const uint32_t timestamp =
                    ahead->timestamp;

                const uint64_t arrival =
                    ahead->arrival_us;

                const int fec_samples =
                    DecodePacket(
                        stream,
                        ahead->data,
                        ahead->size,
                        false,
                        true,
                        arrival);

                if (fec_samples > 0) {
                    stream->next_sequence =
                        static_cast<uint16_t>(
                            stream->next_sequence + 1);

                    stream->next_timestamp += 480;
                } else {
                    DecodePlc(stream);

                    stream->next_sequence =
                        static_cast<uint16_t>(
                            stream->next_sequence + 1);

                    stream->next_timestamp += 480;
                }

                (void)sequence;
                (void)timestamp;

                // The same packet still needs its normal decode.
                // Marking it untouched here lets the exact lookup
                // decode it immediately below.
                continue;
            }

            // More than one missing packet.
            // Fill the missing timeline immediately with PLC.
            DecodePlc(stream);

            stream->next_sequence =
                static_cast<uint16_t>(
                    stream->next_sequence + 1);

            stream->next_timestamp += 480;
        }
    }

    int ReadStream(
        Stream* stream,
        int16_t* mix,
        uint8_t* contributors,
        int frames) {

        uint32_t read =
            stream->pcm_read.load(
                std::memory_order_relaxed);

        const uint32_t write =
            stream->pcm_write.load(
                std::memory_order_acquire);

        int count = 0;

        while (count < frames &&
               read != write) {

            const uint64_t stamp =
                stream->pcm_time_us[read];

            const int32_t value =
                static_cast<int32_t>(mix[count]) +
                static_cast<int32_t>(stream->pcm[read]);

            mix[count] =
                static_cast<int16_t>(
                    std::clamp(
                        value,
                        -32768,
                        32767));

            if (contributors) {
                if (contributors[count] < 255) {
                    ++contributors[count];
                }
            }

            if (Measurements() &&
                stamp != 0) {

                const uint64_t now = NowUs();

                if (now >= stamp) {
                    const uint64_t residence =
                        now - stamp;

                    stats.Residence(residence);
                    stats.PacketToPlay(residence);
                }
            }

            ++count;

            read =
                (read + 1) % kStreamRingFrames;
        }

        stream->pcm_read.store(
            read,
            std::memory_order_release);

        return count;
    }

    int ReadPcm(
        int16_t* output,
        int frames,
        int channels,
        int sample_rate) {

        const uint64_t start =
            Measurements() ? NowUs() : 0;

        if (!output ||
            frames <= 0 ||
            channels <= 0) {
            return 0;
        }

        const size_t total =
            static_cast<size_t>(frames) *
            static_cast<size_t>(channels);

        if (!enabled.load(
                std::memory_order_acquire) ||
            sample_rate != 48000) {

            std::memset(
                output,
                0,
                total * sizeof(int16_t));

            return 0;
        }

        int16_t mix[kOutputChunk];
        uint8_t contributors[kOutputChunk];

        int remaining = frames;
        int offset = 0;

        while (remaining > 0) {
            const int chunk =
                std::min(
                    remaining,
                    kOutputChunk);

            std::memset(
                mix,
                0,
                static_cast<size_t>(chunk) *
                    sizeof(int16_t));

            std::memset(
                contributors,
                0,
                static_cast<size_t>(chunk) *
                    sizeof(uint8_t));

            for (auto& stream : streams) {
                if (!stream.active.load(
                        std::memory_order_acquire)) {
                    continue;
                }

                ReadStream(
                    &stream,
                    mix,
                    contributors,
                    chunk);
            }

            // Count an underrun only when the final mixed output
            // has no source PCM at all.
            uint64_t missing_frames = 0;

            for (int i = 0; i < chunk; ++i) {
                if (contributors[i] == 0) {
                    ++missing_frames;
                }
            }

            if (missing_frames != 0) {
                stats.pcm_underruns.fetch_add(
                    missing_frames);
            }

            for (int i = 0; i < chunk; ++i) {
                const int16_t value =
                    contributors[i] != 0
                        ? mix[i]
                        : 0;

                for (int channel = 0;
                     channel < channels;
                     ++channel) {

                    output[
                        (offset + i) * channels +
                        channel] = value;
                }
            }

            stats.pcm_frames_read.fetch_add(
                static_cast<uint64_t>(chunk));

            offset += chunk;
            remaining -= chunk;
        }

        if (Measurements()) {
            stats.Callback(
                NowUs() - start,
                frames);
        }

        return frames;
    }

};

YasuFastAudioCore&
YasuFastAudioCore::Instance() {
    static YasuFastAudioCore instance;
    return instance;
}

YasuFastAudioCore::YasuFastAudioCore()
    : impl_(new Impl()) {
    impl_->stats.Reset();
}

YasuFastAudioCore::~YasuFastAudioCore() {
    impl_->enabled.store(
        false,
        std::memory_order_release);

    Reset();

    delete impl_;
}

void YasuFastAudioCore::SetEnabled(
    bool enabled) {

    if (enabled) {
        /*
         * Every explicit activation starts with a clean engine.
         * This prevents a previous Group Call from leaking PCM,
         * sequence state, or decoders into the new call.
         */
        impl_->enabled.store(
            false,
            std::memory_order_release);

        Reset();

        impl_->enabled.store(
            true,
            std::memory_order_release);

        return;
    }

    impl_->enabled.store(
        false,
        std::memory_order_release);

    Reset();
}

bool YasuFastAudioCore::IsEnabled() const {
    return impl_->enabled.load(
        std::memory_order_acquire);
}

void YasuFastAudioCore::Reset() {
    impl_->Lock();

    for (auto& stream : impl_->streams) {
        if (stream.decoder) {
            opus_decoder_destroy(
                stream.decoder);

            stream.decoder = nullptr;
        }

        stream.active.store(
            false,
            std::memory_order_release);

        stream.ssrc = 0;

        stream.have_sequence = false;
        stream.next_sequence = 0;

        stream.have_timestamp = false;
        stream.next_timestamp = 0;

        stream.last_packet_us.store(
            0,
            std::memory_order_release);

        stream.pcm_read.store(
            0,
            std::memory_order_release);

        stream.pcm_write.store(
            0,
            std::memory_order_release);
    }

    impl_->stats.Reset();

    impl_->Unlock();
}

void YasuFastAudioCore::PushPacket(
    uint32_t ssrc,
    uint16_t sequence,
    uint32_t timestamp,
    const uint8_t* payload,
    size_t payload_size) {

    if (!IsEnabled() ||
        payload == nullptr ||
        payload_size == 0 ||
        payload_size > kMaxPayload) {
        return;
    }

    const bool measure =
        YasuMeasurementsEnabled();

    const uint64_t arrival =
        NowUs();

    if (measure) {
        impl_->stats.packets_received.fetch_add(1);
    }

    impl_->Lock();

    Stream* stream =
        impl_->Find(ssrc);

    if (!stream) {
        stream =
            impl_->Create(ssrc);
    }

    if (!stream) {
        if (measure) {
            impl_->stats.packets_dropped.fetch_add(1);
        }

        impl_->Unlock();
        return;
    }

    stream->last_packet_us.store(
        arrival,
        std::memory_order_release);

    if (stream->have_sequence) {
        const uint16_t expected =
            stream->next_sequence;

        if (sequence == expected) {
            // Exact next packet.
        } else if (SeqBehind(
                       sequence,
                       expected)) {

            // Already played / no longer useful.
            if (measure) {
                impl_->stats.packets_late.fetch_add(1);
            }

            impl_->Unlock();
            return;

        } else if (SeqAhead(
                       sequence,
                       expected)) {

            if (measure) {
                impl_->stats.packets_reordered.fetch_add(1);
            }
        }
    }

    // Reject duplicate packet already sitting in the reorder slots.
    for (auto& packet : stream->packets) {
        if (packet.valid &&
            packet.sequence == sequence) {

            if (measure) {
                impl_->stats.packets_dropped.fetch_add(1);
            }

            impl_->Unlock();
            return;
        }
    }

    Packet* destination = nullptr;

    for (auto& packet : stream->packets) {
        if (!packet.valid) {
            destination = &packet;
            break;
        }
    }

    if (!destination) {
        /*
         * Buffer is full.
         *
         * Drop the packet farthest ahead instead of destroying
         * the packet closest to playback.
         */
        uint16_t worst_distance = 0;
        Packet* worst = nullptr;

        for (auto& packet : stream->packets) {
            if (!packet.valid) {
                continue;
            }

            const uint16_t distance =
                stream->have_sequence
                    ? SeqForwardDistance(
                          packet.sequence,
                          stream->next_sequence)
                    : 0;

            if (!worst ||
                distance > worst_distance) {
                worst = &packet;
                worst_distance = distance;
            }
        }

        destination = worst;

        if (measure) {
            impl_->stats.packets_dropped.fetch_add(1);
        }
    }

    if (!destination) {
        impl_->Unlock();
        return;
    }

    destination->sequence = sequence;
    destination->timestamp = timestamp;

    destination->size =
        static_cast<uint16_t>(
            payload_size);

    destination->arrival_us = arrival;

    std::memcpy(
        destination->data,
        payload,
        payload_size);

    destination->valid = true;

    impl_->Drain(stream);

    impl_->Unlock();
}

std::string
YasuFastAudioCore::TakeMeasurementLog() {

    if (!YasuMeasurementsEnabled()) {
        return "";
    }

    std::ostringstream out;

    const uint64_t now = NowUs();

    const uint64_t duration =
        impl_->stats.started_us != 0 &&
        now >= impl_->stats.started_us
            ? now - impl_->stats.started_us
            : 0;

    const auto avg =
        [](uint64_t total,
           uint64_t count) {

        return count
            ? (total / count)
            : 0;
    };

    const uint64_t decode_count =
        impl_->stats.decode_count.load();

    const uint64_t packet_to_pcm_count =
        impl_->stats.packet_to_pcm_count.load();

    const uint64_t packet_to_play_count =
        impl_->stats.packet_to_play_count.load();

    const uint64_t residence_count =
        impl_->stats.residence_count.load();

    const uint64_t callback_count =
        impl_->stats.callback_count.load();

    out << "YASU FAST AUDIO MEASUREMENTS\n";
    out << "version=3\n";
    out << "sample_rate=48000\n";
    out << "opus_channels=2\n";
    out << "target_ptime_ms=10\n";
    out << "packet_reorder_slots="
        << kPacketSlots << "\n";
    out << "pcm_ring_frames="
        << kStreamRingFrames << "\n";
    out << "pcm_ring_ms="
        << std::fixed
        << std::setprecision(2)
        << (static_cast<double>(
                kStreamRingFrames) / 48.0)
        << "\n";
    out << "measurement_duration_us="
        << duration << "\n";
    out << "\n";

    out << "[PACKETS]\n";
    out << "received="
        << impl_->stats.packets_received.load()
        << "\n";
    out << "decoded="
        << impl_->stats.packets_decoded.load()
        << "\n";
    out << "plc="
        << impl_->stats.packets_plc.load()
        << "\n";
    out << "fec="
        << impl_->stats.packets_fec.load()
        << "\n";
    out << "late="
        << impl_->stats.packets_late.load()
        << "\n";
    out << "dropped="
        << impl_->stats.packets_dropped.load()
        << "\n";
    out << "reordered="
        << impl_->stats.packets_reordered.load()
        << "\n";
    out << "decode_failed="
        << impl_->stats.packets_decode_failed.load()
        << "\n";
    out << "\n";

    out << "[DECODE]\n";
    out << "count="
        << decode_count
        << "\n";
    out << "avg_us="
        << avg(
            impl_->stats.decode_cost_us.load(),
            decode_count)
        << "\n";
    out << "min_us="
        << (decode_count
                ? impl_->stats.decode_cost_min_us.load()
                : 0)
        << "\n";
    out << "max_us="
        << impl_->stats.decode_cost_max_us.load()
        << "\n";
    out << "\n";

    out << "[PACKET_TO_PCM]\n";
    out << "count="
        << packet_to_pcm_count
        << "\n";
    out << "avg_us="
        << avg(
            impl_->stats.packet_to_pcm_us.load(),
            packet_to_pcm_count)
        << "\n";
    out << "min_us="
        << (packet_to_pcm_count
                ? impl_->stats.packet_to_pcm_min_us.load()
                : 0)
        << "\n";
    out << "max_us="
        << impl_->stats.packet_to_pcm_max_us.load()
        << "\n";
    out << "\n";

    out << "[PACKET_TO_PLAY]\n";
    out << "count="
        << packet_to_play_count
        << "\n";
    out << "avg_us="
        << avg(
            impl_->stats.packet_to_play_us.load(),
            packet_to_play_count)
        << "\n";
    out << "min_us="
        << (packet_to_play_count
                ? impl_->stats.packet_to_play_min_us.load()
                : 0)
        << "\n";
    out << "max_us="
        << impl_->stats.packet_to_play_max_us.load()
        << "\n";
    out << "\n";

    out << "[PCM]\n";
    out << "frames_written="
        << impl_->stats.pcm_frames_written.load()
        << "\n";
    out << "frames_read="
        << impl_->stats.pcm_frames_read.load()
        << "\n";
    out << "underruns="
        << impl_->stats.pcm_underruns.load()
        << "\n";
    out << "overruns="
        << impl_->stats.pcm_overruns.load()
        << "\n";
    out << "overrun_frames="
        << impl_->stats.pcm_overrun_frames.load()
        << "\n";
    out << "max_ring_depth_frames="
        << impl_->stats.max_ring_depth.load()
        << "\n";
    out << "max_ring_depth_ms="
        << std::fixed
        << std::setprecision(2)
        << (static_cast<double>(
                impl_->stats.max_ring_depth.load()) / 48.0)
        << "\n";
    out << "\n";

    out << "[PCM_RESIDENCE]\n";
    out << "sample_observations="
        << residence_count
        << "\n";
    out << "avg_us="
        << avg(
            impl_->stats.residence_us.load(),
            residence_count)
        << "\n";
    out << "min_us="
        << (residence_count
                ? impl_->stats.residence_min_us.load()
                : 0)
        << "\n";
    out << "max_us="
        << impl_->stats.residence_max_us.load()
        << "\n";
    out << "\n";

    out << "[AAUDIO_CALLBACK]\n";
    out << "count="
        << callback_count
        << "\n";
    out << "frames="
        << impl_->stats.callback_frames.load()
        << "\n";
    out << "avg_cost_us="
        << avg(
            impl_->stats.callback_cost_us.load(),
            callback_count)
        << "\n";
    out << "min_cost_us="
        << (callback_count
                ? impl_->stats.callback_cost_min_us.load()
                : 0)
        << "\n";
    out << "max_cost_us="
        << impl_->stats.callback_cost_max_us.load()
        << "\n";
    out << "\n";

    out << "[STREAMS]\n";
    out << "peak_active_streams="
        << impl_->stats.active_streams_peak.load()
        << "\n";
    out << "\n";

    out << "[INTERPRETATION]\n";
    out << "packet_to_pcm_us=RTP arrival to decoded PCM insertion\n";
    out << "packet_to_play_us=RTP arrival to PCM consumption by FAST callback\n";
    out << "pcm_residence_us=buffer residence from RTP arrival timestamp\n";
    out << "decode_cost_us=Opus CPU decode time only\n";
    out << "callback_cost_us=FAST mixing/read CPU time only\n";
    out << "underruns=callback requested audio but stream had no PCM\n";
    out << "overruns=old PCM discarded to prevent latency growth\n";
    out << "fec=Opus in-band FEC recovery attempts\n";
    out << "engine_latency_ms_is_not_network_e2e=true\n";
    out << "policy=LOW_LATENCY_FIRST\n";

    return out.str();
}

}  // namespace tgcalls
